### ISSUE TITLE
Extracting "mean age at menarche" in the menarche_age column 

### ISSUE THREAD

**Issue by wbea101** [wbea101/Periods-Worldwide#2]
got this code from chat_gpt unsure how to read it 

mean_age_menarche_df <- df %>%
  filter(grepl("Mean age at menarche", menarche_age))

# Display the resulting dataframe
print(mean_age_menarche_df)

this is the error I received 

Error in UseMethod("filter") : 
  no applicable method for 'filter' applied to an object o

**Comment by abhatia08** [comment]
I just updated the [data ](https://github.com/wbea101/Periods-Worldwide/tree/main/data)folder to now have a [cleaned_data](https://github.com/wbea101/Periods-Worldwide/tree/main/data/cleaned_data) folder, with the files that contain this data!

**Comment by abhatia08** [comment]
I just updated the [data ](https://github.com/wbea101/Periods-Worldwide/tree/main/data)folder to now have a [cleaned_data](https://github.com/wbea101/Periods-Worldwide/tree/main/data/cleaned_data) folder, with the files that contain this data!
